

on:
  push:
    branches: [ "master"] # change to the branch you wish to deploy from
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
      
    - name: Build the app
      run: npm run build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.6.1
      with:
        folder: dist # The folder the action should deploy.
